name: Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install
        run: go install github.com/sepulsa/vetra

      - name: Vet
        run: go vet -vettool=$(go env GOPATH)/bin/vetra ./...
